import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Golf Fitness | David Zabinski Fitness",
  description:
    "TPI-certified golf fitness training in Houston, TX. Improve your mobility, rotational power, and performance on the course with David Zabinski.",
};

const tpiPrinciples = [
  {
    title: "Body-Swing Connection",
    description:
      "Every swing fault has a physical root cause. TPI's research maps specific body limitations to specific swing characteristics — so instead of guessing, David knows exactly what to fix.",
  },
  {
    title: "Movement Screening",
    description:
      "A full TPI physical screen identifies your mobility restrictions, stability deficits, and asymmetries before a single weight is lifted. Training starts with the truth.",
  },
  {
    title: "Mobility & Stability",
    description:
      "The golf swing demands mobility in the hips, thoracic spine, and shoulders — and stability in the core and lower body to transfer that mobility into power. Both must be trained.",
  },
  {
    title: "Rotational Power",
    description:
      "Clubhead speed is generated by the kinematic sequence — the coordinated rotation of hips, torso, arms, and club. David trains each link in that chain.",
  },
  {
    title: "Injury Prevention",
    description:
      "Most golf injuries are the result of compensation patterns — your body working around a limitation. Eliminate the limitation, eliminate the injury.",
  },
];

const focuses = [
  "Rotational power and speed",
  "Hip and thoracic mobility",
  "Stability and balance",
  "Injury prevention and longevity",
  "Sport-specific strength training",
];

export default function GolfFitnessPage() {
  return (
    <div className="pt-20 md:pt-24">
      {/* Hero */}
      <section className="relative bg-[#1a1a1a] border-b border-[#2a2a2a] overflow-hidden">
        <div className="absolute inset-0">
          <Image src="/images/golf-course-bg.jpg" alt="Golf course at golden hour" fill className="object-cover opacity-100" style={{ objectPosition: '55% 65%' }} priority />
        </div>
        
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 py-32">
          <h1 className="section-title mb-4">Golf Fitness Performance</h1>
          <div className="gold-line mb-6" />
          <p className="text-white text-2xl sm:text-3xl max-w-2xl font-semibold tracking-wide" style={{ textShadow: "1px 2px 8px rgba(0,0,0,0.8)" }}>
            Strength. Mobility. Power.
          </p>
        </div>
      </section>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-20 space-y-20">
        {/* What is Golf Fitness */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">
          <div className="grid grid-cols-2 gap-3">
            <div className="relative aspect-[2/3] overflow-hidden">
              <Image src="/images/golf-portrait-main.jpg" alt="David Zabinski on the golf course" fill className="object-cover object-top" />
            </div>
            <div className="relative aspect-[2/3] overflow-hidden">
              <Image src="/images/golf-impact.jpg" alt="David Zabinski golf swing at Cabo" fill className="object-cover object-center" />
            </div>
          </div>
          <div className="flex flex-col justify-center">
            <h2 className="section-title text-2xl mb-4">What Is Golf Fitness?</h2>
            <div className="gold-line mb-6" />
            <p className="text-[#e5e5e5] text-lg leading-relaxed">
              Golf fitness training is the bridge between your body and your
              game. Most golfers spend hours on the range but neglect the
              physical limitations that are holding their swing back. David&apos;s
              golf fitness approach identifies and fixes those limitations —
              improving mobility, stability, rotational power, and injury
              resilience.
            </p>
          </div>
        </section>

        <div className="border-t border-[#2a2a2a]" />

        {/* TPI Certified */}
        <section className="grid grid-cols-1 md:grid-cols-5 gap-10 items-start">
          <div className="md:col-span-2">
            <h2 className="section-title text-2xl mb-4">TPI Certified</h2>
            <div className="gold-line" />
            <div className="mt-6 inline-block bg-[#CC0000]/10 border border-[#CC0000] px-4 py-2">
              <span className="text-[#CC0000] text-xs font-bold tracking-[0.2em] uppercase">
                Titleist Performance Institute
              </span>
            </div>
          </div>
          <div className="md:col-span-3">
            <p className="text-[#e5e5e5] text-lg leading-relaxed">
              David holds the Titleist Performance Institute (TPI) Fitness Coach
              certification — the same credential used by trainers working with
              PGA Tour professionals. TPI&apos;s methodology connects physical
              movement patterns directly to swing characteristics, allowing David
              to identify exactly what your body is preventing your game from
              doing.
            </p>
          </div>
        </section>

        <div className="border-t border-[#2a2a2a]" />

        {/* The TPI Difference — expanded section */}
        <section>
          <div className="mb-10">
            <h2 className="section-title text-3xl mb-4">The TPI Difference</h2>
            <div className="gold-line mb-6" />
            <p className="text-[#e5e5e5] text-lg leading-relaxed max-w-3xl">
              The Titleist Performance Institute has studied over{" "}
              <span className="text-white font-bold">50,000 golfers</span> —
              from weekend amateurs to the world&apos;s best PGA Tour players.
              What they found is that{" "}
              <span className="text-white font-bold">
                there is no single perfect golf swing
              </span>
              , but there is a most efficient swing for every body. TPI&apos;s
              research directly links specific physical limitations to specific
              swing faults. When your hips can&apos;t rotate, your swing
              compensates. When your thoracic spine is locked up, your swing
              compensates. The same methodology used by coaches on the PGA Tour
              is what David applies to every golf fitness client.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-10">
            {tpiPrinciples.map((principle) => (
              <div
                key={principle.title}
                className="bg-[#1a1a1a] border border-[#2a2a2a] p-8 hover:border-[#CC0000] transition-colors"
              >
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-[#CC0000] text-xl flex-shrink-0">▸</span>
                  <h3 className="text-white font-bold text-base uppercase tracking-wide">
                    {principle.title}
                  </h3>
                </div>
                <p className="text-[#a0a0a0] leading-relaxed text-sm">
                  {principle.description}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-8 bg-[#CC0000]/5 border border-[#CC0000] p-8">
            <p className="text-[#e5e5e5] text-lg leading-relaxed">
              <span className="text-[#CC0000] font-bold">Bottom line:</span> If
              your body can&apos;t do it, your swing can&apos;t do it. TPI gives
              David the tools to assess where your body is limiting your game —
              and the programming to fix it.
            </p>
          </div>
        </section>

        <div className="border-t border-[#2a2a2a]" />

        {/* Training Focuses */}
        <section>
          <div className="text-center mb-12">
            <h2 className="section-title mb-4">Training Focuses</h2>
            <div className="gold-line mx-auto" />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {focuses.map((focus) => (
              <div
                key={focus}
                className="bg-[#1a1a1a] border border-[#2a2a2a] px-6 py-5 flex items-center gap-4 hover:border-[#CC0000] transition-colors"
              >
                <span className="text-[#CC0000] text-xl flex-shrink-0">⛳</span>
                <span className="text-[#e5e5e5] font-semibold">{focus}</span>
              </div>
            ))}
          </div>
        </section>

        <div className="border-t border-[#2a2a2a]" />

        {/* David's Golf Background */}
        <section className="grid grid-cols-1 lg:grid-cols-5 gap-10 items-center">
          <div className="lg:col-span-2 relative aspect-[3/4] overflow-hidden">
            <Image src="/images/golf-rangefinder.jpg" alt="David Zabinski on the golf course" fill className="object-cover object-center" />
          </div>
          <div className="lg:col-span-3">
            <h2 className="section-title text-2xl mb-4">David&apos;s Golf Background</h2>
            <div className="gold-line mb-6" />
            <p className="text-[#e5e5e5] text-lg leading-relaxed mb-5">
              David&apos;s connection to golf goes back long before the gym. Growing up, he competed in Junior HGA and STPGA tournaments, developing a deep, firsthand understanding of what the game demands from the body.
            </p>
            <p className="text-[#e5e5e5] text-lg leading-relaxed mb-5">
              That competitive background is what drives his passion for golf fitness — he&apos;s not a trainer who read about the golf swing in a textbook. He lived it. He knows the frustration of physical limitations holding your game back, and he knows what it feels like when the body finally moves the way it&apos;s supposed to.
            </p>
            <p className="text-[#e5e5e5] text-lg leading-relaxed">
              When David trains a golfer, he&apos;s drawing on decades of experience on both sides of the equation — as a competitive player and as a TPI-certified fitness coach.
            </p>
          </div>
        </section>

        <div className="border-t border-[#2a2a2a]" />

        {/* Who This Is For */}
        <section className="bg-[#1a1a1a] border border-[#2a2a2a] p-10">
          <h2 className="text-xl font-bold uppercase tracking-wide text-white mb-4">
            Who This Is For
          </h2>
          <p className="text-[#e5e5e5] text-lg leading-relaxed mb-8">
            Whether you&apos;re a serious amateur trying to break 80 or a
            competitive player looking for every edge, golf fitness training
            delivers measurable results on the course. No golf experience
            required — just the desire to play better.
          </p>
          <Link href="/contact" className="btn-primary">
            Book a Golf Fitness Assessment
          </Link>
        </section>
      </div>
    </div>
  );
}
